export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const LOGOUT = 'LOGOUT';

export const GET_CURRENTUSER_REQUEST = 'GET_CURRENTUSER_REQUEST';
export const GET_CURRENTUSER_FAILURE = 'GET_CURRENTUSER_FAILURE';
export const GET_CURRENTUSER_SUCCESS = 'GET_CURRENTUSER_SUCCESS';

export const EDIT_USERINFO_REQUEST = 'EDIT_USERINFO_REQUEST';
export const EDIT_USERINFO_FAILURE = 'EDIT_USERINFO_FAILURE';
export const EDIT_USERINFO_SUCCESS = 'EDIT_USERINFO_SUCCESS';

export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';

export const GET_USERINFO_REQUEST = 'GET_USERINFO_REQUEST';
export const GET_USERINFO_FAILURE = 'GET_USERINFO_FAILURE';
export const GET_USERINFO_SUCCESS = 'GET_USERINFO_SUCCESS';

export const ADD_USER_REQUEST = 'ADD_USER_REQUEST';
export const ADD_USER_FAILURE = 'ADD_USER_FAILURE';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';

export const UPDATE_ACCOUNTSTATUS_REQUEST = 'UPDATE_ACCOUNTSTATUS_REQUEST';
export const UPDATE_ACCOUNTSTATUS_FAILURE = 'UPDATE_ACCOUNTSTATUS_FAILURE';
export const UPDATE_ACCOUNTSTATUS_SUCCESS = 'UPDATE_ACCOUNTSTATUS_SUCCESS';

export const INVITE_USERS_REQUEST = 'INVITE_USERS_REQUEST';
export const INVITE_USERS_FAILURE = 'INVITE_USERS_FAILURE';
export const INVITE_USERS_SUCCESS = 'INVITE_USERS_SUCCESS';