export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const SET_LOGGEDIN_USER = 'SET_LOGGEDIN_USER';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const GET_CURRENTUSER_REQUEST = 'GET_CURRENTUSER_REQUEST';
export const GET_CURRENTUSER_FAILURE = 'GET_CURRENTUSER_FAILURE';
export const GET_CURRENTUSER_SUCCESS = 'GET_CURRENTUSER_SUCCESS';

export const EDIT_USERINFO_REQUEST = 'EDIT_USERINFO_REQUEST';
export const EDIT_USERINFO_FAILURE = 'EDIT_USERINFO_FAILURE';
export const EDIT_USERINFO_SUCCESS = 'EDIT_USERINFO_SUCCESS';

export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';

export const GET_USERINFO_REQUEST = 'GET_USERINFO_REQUEST';
export const GET_USERINFO_FAILURE = 'GET_USERINFO_FAILURE';
export const GET_USERINFO_SUCCESS = 'GET_USERINFO_SUCCESS';

export const ADD_USER_REQUEST = 'ADD_USER_REQUEST';
export const ADD_USER_FAILURE = 'ADD_USER_FAILURE';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';

export const UPDATE_ACCOUNTSTATUS_REQUEST = 'UPDATE_ACCOUNTSTATUS_REQUEST';
export const UPDATE_ACCOUNTSTATUS_FAILURE = 'UPDATE_ACCOUNTSTATUS_FAILURE';
export const UPDATE_ACCOUNTSTATUS_SUCCESS = 'UPDATE_ACCOUNTSTATUS_SUCCESS';

export const INVITE_USERS_REQUEST = 'INVITE_USERS_REQUEST';
export const INVITE_USERS_FAILURE = 'INVITE_USERS_FAILURE';
export const INVITE_USERS_SUCCESS = 'INVITE_USERS_SUCCESS';

export const GET_EVENTS_REQUEST = 'GET_EVENTS_REQUEST';
export const GET_EVENTS_FAILURE = 'GET_EVENTS_FAILURE';
export const GET_EVENTS_SUCCESS = 'GET_EVENTS_SUCCESS';

export const INSTITUTION_REQUEST = 'INSTITUTION_REQUEST';
export const INSTITUTION_FAILURE = 'INSTITUTION_FAILURE';
export const INSTITUTION_SUCCESS = 'INSTITUTION_SUCCESS';

export const IMG_REQUEST = 'IMG_REQUEST';
export const IMG_FAILURE = 'IMG_FAILURE';
export const IMG_SUCCESS = 'IMG_SUCCESS';

export const EVENTS_REQUEST = 'EVENTS_REQUEST';
export const EVENTS_FAILURE = 'EVENTS_FAILURE';
export const EVENTS_SUCCESS = 'EVENTS_SUCCESS';

export const BOOKING_REQUEST = 'BOOKING_REQUEST';
export const BOOKING_FAILURE = 'BOOKING_FAILURE';
export const BOOKING_SUCCESS = 'BOOKING_SUCCESS';

export const ADD_BOOKING_REQUEST = 'ADD_BOOKING_REQUEST';
export const ADD_BOOKING_FAILURE = 'ADD_BOOKING_FAILURE';
export const ADD_BOOKING_SUCCESS = 'ADD_BOOKING_SUCCESS';

export const ADD_BOOKING_NOTES_REQUEST = 'ADD_BOOKING_NOTES_REQUEST';
export const ADD_BOOKING_NOTES_FAILURE = 'ADD_BOOKING_NOTES_FAILURE';
export const ADD_BOOKING_NOTES_SUCCESS = 'ADD_BOOKING_NOTES_SUCCESS';

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';

export const ADD_INSTITUTION_REQUEST = 'ADD_INSTITUTION_REQUEST';
export const ADD_INSTITUTION_FAILURE = 'ADD_INSTITUTION_FAILURE';
export const ADD_INSTITUTION_SUCCESS = 'ADD_INSTITUTION_SUCCESS';

export const GET_MULTIPLE_EVENTS_REQUEST = 'GET_MULTIPLE_EVENTS_REQUEST';
export const GET_MULTIPLE_EVENTS_FAILURE = 'GET_MULTIPLE_EVENTS_FAILURE';
export const GET_MULTIPLE_EVENTS_SUCCESS = 'GET_MULTIPLE_EVENTS_SUCCESS';

export const UPLOAD_REQUEST = 'UPLOAD_REQUEST';
export const UPLOAD_FAILURE = 'UPLOAD_FAILURE';
export const UPLOAD_SUCCESS = 'UPLOAD_SUCCESS';

export const REPORT_REQUEST = 'REPORT_REQUEST';
export const REPORT_FAILURE = 'REPORT_FAILURE';
export const REPORT_SUCCESS = 'REPORT_SUCCESS';

export const PASSWORD_UPDATE_REQUEST = 'PASSWORD_UPDATE_REQUEST';
export const PASSWORD_UPDATE_FAILURE = 'PASSWORD_UPDATE_FAILURE';
export const PASSWORD_UPDATE_SUCCESS = 'PASSWORD_UPDATE_SUCCESS';
export const NOTIFICATION_REQUEST = 'NOTIFICATION_REQUEST';
export const NOTIFICATION_FAILURE = 'NOTIFICATION_FAILURE';
export const NOTIFICATION_SUCCESS = 'NOTIFICATION_SUCCESS';
