export { loginUser, logoutUser } from './auth';
export { getInstitution } from './institution';
export { addInstitution } from './addInstitution';
export { addUser } from './user';
export { getLatestEvents } from './event';
export { setBookings, book, setNotes } from './booking';
export { updateUser } from './updateUser';
export { getMultipleLatestEvents } from './multipleEvent';
export { upload } from './upload';
export { getReports } from './report';
